"""Render roadmap.md, in the root of the repository.

The order is reasoned rather than computed, so it will differ between runs.
The file is therefore built to be reviewed: it says when it was made, what it
was made from, and why each ordering call was made.
"""


def _parse_home(home):
    """Parse home parameter into (owner, repo).

    Accepts either a tuple/list of (owner, repo) or a string "owner/repo".
    """
    if isinstance(home, str):
        owner, repo = home.split("/")
        return (owner, repo)
    return tuple(home)


def _format_ref(ref, home_owner, home_repo):
    """Format a Ref for display in the roadmap.

    Same-repo references render as #number.
    Cross-repo references render as owner/repo#number.
    Per-reference formatting ensures adding a cross-repo blocker does not
    change the format of every other issue, keeping diffs reviewable.
    """
    if ref.owner == home_owner and ref.repo == home_repo:
        return f"#{int(ref.number)}"
    return str(ref)


def render(g, titles, reasons, triage, generated, issue_count, home):
    """Render a roadmap.

    Args:
        g: The dependency graph (Graph object)
        titles: Dict mapping Ref to title string
        reasons: Dict mapping Ref to reasoning string
        triage: List of Ref objects in triage (unreviewed)
        generated: datetime.date of when this was generated
        issue_count: Total count of open issues
        home: Home repository as tuple (owner, repo) or string "owner/repo"

    Returns:
        Complete markdown roadmap as a string
    """
    home_owner, home_repo = _parse_home(home)

    def fmt(ref):
        return _format_ref(ref, home_owner, home_repo)

    out = ["# Roadmap", ""]
    out.append(
        f"Generated by deskwork on {generated.isoformat()} "
        f"from {issue_count} open issues."
    )
    out.append(
        "Order is reasoned, not computed. Every dependency shown is a declared "
        "GitHub link."
    )
    out.append("")

    out.append("## Next")
    out.append("")
    ready = g.ready()
    if not ready:
        out.append("Nothing is ready. Everything open is blocked.")
        out.append("")
    for position, ref in enumerate(ready, start=1):
        out.append(f"{position}. **{fmt(ref)}** {titles.get(ref, '')}".rstrip())
        reason = reasons.get(ref)
        if reason:
            out.append(f"   {reason}")
    out.append("")

    blocked = g.blocked()
    if blocked:
        out.append("## Blocked")
        out.append("")
        for ref in blocked:
            blockers = ", ".join(
                f"blocked by {fmt(b)}" for b in sorted(g.edges[ref], key=str)
            )
            out.append(f"- **{fmt(ref)}** {titles.get(ref, '')} - {blockers}")
        out.append("")

    cycles = g.cycles()
    if cycles:
        out.append("## Cycles")
        out.append("")
        out.append("These block each other. Nothing can be ordered until one link goes.")
        out.append("")
        for cycle in cycles:
            out.append("- " + " -> ".join(fmt(node) for node in cycle))
        out.append("")

    bottlenecks = g.bottlenecks()
    if bottlenecks:
        out.append("## Bottlenecks")
        out.append("")
        for ref, count in bottlenecks:
            out.append(f"- **{fmt(ref)}** blocks {count} issues")
        out.append("")

    out.append("## Triage - not yet in the roadmap")
    out.append("")
    out.append(
        "Filed by an agent and not yet reviewed. Listed, never ordered."
        if triage else "Nothing waiting."
    )
    out.append("")
    for ref in triage:
        out.append(f"- {fmt(ref)} {titles.get(ref, '')}".rstrip())
    return "\n".join(out).rstrip() + "\n"
