"""Render roadmap.md, in the root of the repository.

The order is reasoned rather than computed, so it will differ between runs.
The file is therefore built to be reviewed: it says when it was made, what it
was made from, and why each ordering call was made.
"""


def _format_ref(ref, home_owner=None, home_repo=None):
    """Format a Ref for display in the roadmap.

    If the Ref is from the home repository, render as #number.
    If it is from a different repository, render as owner/repo#number.
    This ensures a reader never has to guess which repository a number belongs to.
    """
    if home_owner and home_repo and ref.owner == home_owner and ref.repo == home_repo:
        return f"#{int(ref.number)}"
    return str(ref)


def _infer_home_repo(g):
    """Infer the home repository from the graph.

    Returns (owner, repo) if all issues in the roadmap are from the same repo,
    or (None, None) if there are cross-repo issues or no issues.
    """
    if not g.edges:
        return (None, None)

    first_ref = next(iter(g.edges))
    home_owner = first_ref.owner
    home_repo = first_ref.repo

    # Check if all refs are from the same repo
    for ref in g.edges:
        if ref.owner != home_owner or ref.repo != home_repo:
            # Cross-repo references exist, use full format for all
            return (None, None)

    return (home_owner, home_repo)


def render(g, titles, reasons, triage, generated, issue_count):
    home_owner, home_repo = _infer_home_repo(g)

    def fmt(ref):
        return _format_ref(ref, home_owner, home_repo)

    out = ["# Roadmap", ""]
    out.append(
        f"Generated by deskwork on {generated.isoformat()} "
        f"from {issue_count} open issues."
    )
    out.append(
        "Order is reasoned, not computed. Every dependency shown is a declared "
        "GitHub link."
    )
    out.append("")

    out.append("## Next")
    out.append("")
    ready = g.ready()
    if not ready:
        out.append("Nothing is ready. Everything open is blocked.")
        out.append("")
    for position, ref in enumerate(ready, start=1):
        out.append(f"{position}. **{fmt(ref)}** {titles.get(ref, '')}".rstrip())
        reason = reasons.get(ref)
        if reason:
            out.append(f"   {reason}")
    out.append("")

    blocked = g.blocked()
    if blocked:
        out.append("## Blocked")
        out.append("")
        for ref in blocked:
            blockers = ", ".join(
                f"blocked by {fmt(b)}" for b in sorted(g.edges[ref], key=str)
            )
            out.append(f"- **{fmt(ref)}** {titles.get(ref, '')} - {blockers}")
        out.append("")

    cycles = g.cycles()
    if cycles:
        out.append("## Cycles")
        out.append("")
        out.append("These block each other. Nothing can be ordered until one link goes.")
        out.append("")
        for cycle in cycles:
            out.append("- " + " -> ".join(fmt(node) for node in cycle))
        out.append("")

    bottlenecks = g.bottlenecks()
    if bottlenecks:
        out.append("## Bottlenecks")
        out.append("")
        for ref, count in bottlenecks:
            out.append(f"- **{fmt(ref)}** blocks {count} issues")
        out.append("")

    out.append("## Triage - not yet in the roadmap")
    out.append("")
    out.append(
        "Filed by an agent and not yet reviewed. Listed, never ordered."
        if triage else "Nothing waiting."
    )
    out.append("")
    for ref in triage:
        out.append(f"- {fmt(ref)} {titles.get(ref, '')}".rstrip())
    return "\n".join(out).rstrip() + "\n"
